(define (domain sokoban-domain)
  (:requirements :equality)
  (:predicates (adj ?x ?y) (hasAgent ?x) (hasBlock ?x) (collinear ?a ?b ?c))
  (:action move-box
           :parameters (?a ?b ?c)
           :precondition (and (hasAgent ?a)
           					  (hasBlock ?b)
           					  (not (hasAgent ?c) )
           					  (not (hasBlock ?c) )
           					  (adj ?a ?b)
           					  (adj ?b ?c)
           					  (collinear ?a ?b ?c)
           				 )
           :effect (and (hasBlock ?c)
           				(hasAgent ?b)
           				(not (hasAgent ?a))
           				(not (hasBlock ?b))
                   )
   )
                        
  (:action move-agent
           :parameters (?a ?c)
           :precondition (and (hasAgent ?a)
           					  (not (hasBlock ?c) )
           					  (adj ?a ?c)
           				 )
           :effect (and (hasAgent ?c)
           				(not (hasAgent ?a))
                   )
   )
                        
)
