(define (problem sokoban)
  (:domain sokoban-domain)
  (:objects c1 c2 c3 c4)
  (:init (hasAgent c1) (not (hasBlock c1)) 
  	     (hasBlock c2) (not (hasAgent c2)) 
  		 (not (hasBlock c3)) (not (hasAgent c3))
  		 (not (hasBlock c4)) (not (hasAgent c4)) 
  		 (adj c1 c2) (adj c2 c1) (adj c2 c3) (adj c3 c2)
  		 (adj c3 c4) (adj c4 c3)
  		 (collinear c1 c2 c3) 
  		 (collinear c2 c3 c4) 
  )
  (:goal ( hasBlock c4 ) )
)
